### PR TITLE
Update nikic/php-parser to 1.3.*

### PR DESCRIPTION
**Pull request by tamcap**
* Update MethodDisablerVisitor.php and composer.json
* This commit is consistent with the changes made in php-parser v. 1.3
 which also makes the whole thing php7 compatible

### CODE REVIEW

**Comment by tamcap** [comment]
Not sure what to do with the failing hhvm build :-1:

**Comment by Ocramius** [comment]
Seems related only to coverage.

Can't check it myself right now, but if you want, you can try putting a conditional around the execution, and run coverage checks only on 5.6

**Comment by Ocramius** [comment]
@malukenho can you eventually look into it?

**Comment by tamcap** [comment]
Restarting travis.

**Comment by Ocramius** [comment]
Restarted

**Comment by tamcap** [comment]
Travis-CI is having a terribly bad day, it seems.

**Comment by Ocramius** [comment]
About time :P Merging!

**Comment by tamcap** [comment]
Thanks for all the help!

**Comment by Ocramius** [comment]
Tagged [0.3.2](https://github.com/Ocramius/CodeGenerationUtils/releases/tag/0.3.2)

**Pull request merged**
