### PR TITLE
allow nikic/php-parser 1.1

### PR DESCRIPTION
**Pull request by remicollet**
$ vendor/bin/phpunit 
    PHPUnit 4.7-g7b9e68d by Sebastian Bergmann and contributors.
    
    Configuration read from /work/GIT/CodeGenerationUtils/phpunit.xml.dist
    
    ...........S..............................I...................... 65 / 71 ( 91%)
    ......
    
    Time: 120 ms, Memory: 11.00Mb

There was 1 incomplete test:
1) CodeGenerationUtilsTest\Visitor\ClassClonerVisitorTest::testClonesClassIntoNonEmptyNodeList
Still not clear thoughts on this...

There was 1 skipped test:
1) CodeGenerationUtilsTest\GeneratorStrategy\EvaluatingGeneratorStrategyTest::testGenerateWithDisabledEval
Ini setting "suhosin.executor.disable_eval" is needed to run this test

### CODE REVIEW

**Comment by remicollet** [comment]
I don't know if you prefer ~1.0 (<2) of only 1.0 or 1.1

**Comment by Ocramius** [comment]
I'm actually fine with `~1.0`

**Comment by remicollet** [comment]
> I'm actually fine with ~1.0
Done

**Comment by Ocramius** [comment]
Thanks @remicollet! Waiting for travis and then merging :)

**Comment by Ocramius** [comment]
Done in release [0.3.1](https://github.com/Ocramius/CodeGenerationUtils/releases/tag/0.3.1)

**Pull request merged**
